//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HalifaxScienceLibrary_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int trn_code { get; set; }
        public string date { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<int> cust_id { get; set; }
    
        public virtual customer customer { get; set; }
    }
}
